name: Continuous Integration


# Starts workflow upon commit to main, directly or merged in (I think IDK)
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build Docker image
      run: |
        docker build -t my-app:$GITHUB_SHA .

    - name: Test Docker image
      run: |
        docker run my-app:$GITHUB_SHA
